baseURL = 'https://akorzunin.github.io/cv/'
languageCode = 'en-us'
title = 'Alexey Korzunin'
theme = 'hugo-coder'
defaultContentLanguage = "en"
enableEmoji = true
[pagination]
pagerSize = 20

[markup.highlight]
noClasses = false

[params]
author = "Alexey Korzunin"
description = "Alexey Korzunin's personal website"
keywords = "blog,developer,personal"
info = ["Back-end developer"]
avatarURL = "images/avatar.png"
favicon_32 = "/cv/favicon.ico"
favicon_16 = "/cv/favicon.ico"
# Git Commit in Footer, uncomment the line below to enable it
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 10
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/akorzunin/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/alexey-korzunin-297b22219/"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 5
url = "https://t.me/akorzunin"

[[params.social]]
name = "Gmail"
icon = "fa fa-2x fa-envelope-open"
weight = 6
url = "mailto:akorzunin123@gmail.com"


[languages.ru-ru.params]
author = "Корзунин Алексей"
info = "Full-stack разработчик"

# [[languages.en.menu.main]]
# name = "Resume"
# weight = 1
# url = "resume/"

# [[languages.ru-ru.menu.main]]
# name = "Резюме"
# weight = 1
# url = "resume/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.ru-ru.menu.main]]
name = "Проекты"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 3
url = "contact/"

[[languages.ru-ru.menu.main]]
name = "Контакты"
weight = 3
url = "contact/"

# [languages.en]
# languageName = "to English"

# [languages.ru-ru]
# languageName = "to Russian"
# title = "Корзунин Алексей"

# [markup]
# [markup.goldmark]
# [markup.goldmark.renderer]
# unsafe = true
