version: "3"

vars:
  SANITIZE_FILES_INPUT: $( find ./content/parts ./content/r -type f -name '*.md' )

tasks:
  sanitize-files:
    desc: Sanitize files
    aliases:
      - sf
    cmds:
      - python ./pandoc/sanitize_parts.py {{ .SANITIZE_FILES_INPUT }}

  generate-all-docs:
    aliases:
      - all
    desc: Generate all files
    deps:
      - sanitize-files
    cmds:
      - python ./pandoc/generate_docs.py ./content/r

  debug-hugo:
    desc: Serve site
    aliases:
      - dh
    cmds:
      - hugo server -D --disableFastRender

  setup-hugo:
    desc: Setup hugo
    vars:
      HUGO_VERSION: 0.134.1
    cmds:
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@v{{ .HUGO_VERSION }}

  setup-pandoc:
    desc: Setup pandoc
    vars:
      PANDOC_VERSION: "3.1"
    cmds:
      - docker build -t local-pandoc:{{ .PANDOC_VERSION }} .
      - echo '#!/usr/bin/env bash' > ~/.local/bin/pandoc
      - echo 'docker run --rm --volume $(pwd):/data local-pandoc:{{ .PANDOC_VERSION }} $@' >> ~/.local/bin/pandoc
      - chmod +x ~/.local/bin/pandoc
