on:
  push:
    branches:
      - never

jobs:
  pandoc-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: arduino/setup-task@v2

      - uses: pandoc/actions/setup@v1
        with:
          version: 3.2

      - name: install pdf engine and fonts
        run: >-
          sudo apt-get install -y
          texlive-xetex
          texlive-lang-cyrillic
          fonts-open-sans

      - name: Buld all files w/ pandoc
        run: task all

      - uses: actions/upload-artifact@v4.4.0
        with:
          name: output
          path: ./static/files
          retention-days: 1
