name: pandoc

on:
  push:
    branches:
      - test

jobs:
  run-pandoc:
    name: run pandoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.9.2.1"
      - name: install pdf engine
        run: sudo apt-get install -y texlive-xetex
      - name: install pdf lang
        run: sudo apt-get install -y texlive-lang-cyrillic
      - name: install fonts
        run: sudo apt-get install -y fonts-open-sans
      - name: mkdir
        run: mkdir -p ./static/files
      - name: generate pdf
        run: >-
          pandoc
          --pdf-engine=xelatex
          ./content/export/resume.md
          -s
          -o ./static/files/resume.pdf
      - name: generate ru pdf
        run: >-
          pandoc
          --pdf-engine=xelatex
          ./content/export/resume.ru-ru.md -s
          -o ./static/files/resume.ru-ru.pdf
      - name: generate md
        run: >-
          pandoc
          -f markdown+smart
          ./content/export/resume.md
          -o ./static/files/resume.md
      - name: generate ru md
        run: >-
          pandoc
          -f markdown+smart
          ./content/export/resume.ru-ru.md
          -o ./static/files/resume.ru-ru.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: ./static/files
          retention-days: 1

  echo-artifacts:
    runs-on: ubuntu-latest
    needs: [run-pandoc]
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: output
          path: ./static/files

      - run: ls ./static/files -lah
